create table if not exists public.games (
  universe_id bigint primary key,
  root_place_id bigint,
  name text not null,
  description text,
  creator_name text,
  creator_id bigint,
  visits bigint not null default 0 check (visits >= 0),
  playing integer not null default 0 check (playing >= 0),
  favorites bigint not null default 0 check (favorites >= 0),
  genre text,
  created timestamptz,
  updated timestamptz,
  icon_url text,
  thumbnail_url text,
  discord text,
  source text not null default 'roblox',
  keywords text[] not null default '{}',
  metadata jsonb not null default '{}'::jsonb,
  ingested_at timestamptz not null default now()
);

create table if not exists public.game_snapshots (
  id bigint generated by default as identity primary key,
  universe_id bigint not null references public.games(universe_id) on delete cascade,
  playing integer not null check (playing >= 0),
  visits bigint not null check (visits >= 0),
  captured_at timestamptz not null default now()
);

create index if not exists games_visits_idx on public.games (visits);
create index if not exists games_playing_idx on public.games (playing);
create index if not exists games_updated_idx on public.games (updated desc);
create index if not exists game_snapshots_universe_captured_idx on public.game_snapshots (universe_id, captured_at desc);

alter table public.games enable row level security;
alter table public.game_snapshots enable row level security;

drop policy if exists "Public can read games" on public.games;
create policy "Public can read games" on public.games for select to anon, authenticated using (true);

drop policy if exists "Public can read game snapshots" on public.game_snapshots;
create policy "Public can read game snapshots" on public.game_snapshots for select to anon, authenticated using (true);

revoke all on public.games from anon, authenticated;
revoke all on public.game_snapshots from anon, authenticated;
grant select on public.games to anon, authenticated;
grant select on public.game_snapshots to anon, authenticated;

create or replace view public.game_catalog_stats with (security_invoker = true) as
select
  count(*)::bigint as total_games,
  count(*) filter (where playing >= 100)::bigint as high_ccu,
  count(*) filter (where visits < 5000000 and playing >= 100)::bigint as hidden_gems,
  coalesce(round(avg(playing)), 0)::integer as avg_ccu,
  coalesce(max(case when visits > 0 then playing::numeric / visits else 0 end), 0)::numeric as top_ratio
from public.games;

grant select on public.game_catalog_stats to anon, authenticated;
